### ISSUE TITLE
endophile can't initialise when imported into project

### ISSUE THREAD

**Issue by hermann-p** [theJohnnyBrown/endophile#17]
From inside a clone of the repo:

```
user=> (require '[endophile.core :refer [mp]])
nil
user=> (mp "foo")
#object[org.pegdown.ast.RootNode 0x335e3171 "RootNode [0-3]"]
user=>
```

From inside a project with `[endophile "0.2.1"]` dependency:

```
user=> (require '[endophile.core :refer [mp]])
nil
user=> (mp "foo")

IllegalArgumentException   org.objectweb.asm.MethodVisitor.<init> (:-1)
```

When I try to parse a java.lang.String returned from a postgres-database request I run into #16.

```
(ns my-ns
  (:require [endophile.core :refer [mp]]
            [endophile.hiccup :refer [to-hiccup]]))

(-> content
      mp
      to-hiccup)
```

> SEVERE: #error {
>  :cause nil
>  :via
>  [{:type java.lang.RuntimeException
>    :message Error creating extended parser class: null
>    :at [org.parboiled.Parboiled createParser Parboiled.java 58]}
>   {:type java.lang.IllegalArgumentException
>    :message nil
>    :at [org.objectweb.asm.MethodVisitor <init> nil -1]}]
>  :trace
>  [[org.objectweb.asm.MethodVisitor <init> nil -1]
>   [org.objectweb.asm.MethodVisitor <init> nil -1]
>   [org.objectweb.asm.tree.MethodNode <init> nil -1]
>   [org.objectweb.asm.tree.MethodNode <init> nil -1]
>   [org.parboiled.transform.ClassNodeInitializer visitMethod ClassNodeInitializer.java 136]
>   [org.objectweb.asm.ClassReader b nil -1]
>   [org.objectweb.asm.ClassReader accept nil -1]
>   [org.objectweb.asm.ClassReader accept nil -1]
>   [org.parboiled.transform.ClassNodeInitializer process ClassNodeInitializer.java 63]
>   [org.parboiled.transform.ParserTransformer extendParserClass ParserTransformer.java 44]
>   [org.parboiled.transform.ParserTransformer transformParser ParserTransformer.java 38]
>   [org.parboiled.Parboiled createParser Parboiled.java 54]
>   [org.pegdown.PegDownProcessor <init> PegDownProcessor.java 94]
>   [org.pegdown.PegDownProcessor <init> PegDownProcessor.java 63]
>   [sun.reflect.NativeConstructorAccessorImpl newInstance0 NativeConstructorAccessorImpl.java -2]
>   [sun.reflect.NativeConstructorAccessorImpl newInstance NativeConstructorAccessorImpl.java 62]
>   [sun.reflect.DelegatingConstructorAccessorImpl newInstance DelegatingConstructorAccessorImpl.java 45]
>   [java.lang.reflect.Constructor newInstance Constructor.java 423]
>   [clojure.lang.Reflector invokeConstructor Reflector.java 180]
>   [endophile.core$mp invokeStatic core.clj 71]
>   [endophile.core$mp invoke core.clj 60]
>   [endophile.core$mp invokeStatic core.clj 68]
>   [endophile.core$mp invoke core.clj 60]
>   [main.pages$eval11415$fn__11417 invoke pages.clj 10]
>   [clojure.lang.MultiFn invoke MultiFn.java 233]
>   [main.pages$mk_page invokeStatic pages.clj 35]
> 

Tell me if I can do anything to help you track that down (or scold me if I'm using endophile wrong).

**Comment by Deraen** [comment]
Check `lein deps :tree` / `boot show -d` to validate if you have dependency confict, i.e. some other lib than endophile is bringing up different version of parboiled or asm dependency.

**Comment by hermann-p** [comment]
You're right. Fighwheel still seems to use `asm-all 4.2`

**Comment by theJohnnyBrown** [comment]
@hermann-p have you figured this out? You  might want to specify the version in your project.clj to resolve the conflict

**Comment by hermann-p** [comment]
I still wasn't able to resolve the conflicts. Do you suggest specifying an asm-all version to override figwheel's? Endophile's 5.x above figwheel's 4.x seems to signal a release with breaking changes included. Just for testing, is there a way to override a dependency's dependencies?

**Comment by Deraen** [comment]
@hermann-p Yes, just add asm-all dependency to your project. Local dependencies always override transitive deps.

**Comment by hermann-p** [comment]
Thanks for the information @Deraen I didn't know about that. Adding `[asm-all "5.0.3"]` dep to `project.clj` made endophile work perfectly. Maybe this shoul be mentioned in your readme, for others using endophile on the backend and fighweel on the frontend in the same project.

**Comment by hermann-p** [comment]
To be exact about "work perfectly": the errors from closed #16 won't occur anymore, either.

**Comment by Deraen** [comment]
https://github.com/theJohnnyBrown/endophile/commit/09350a642dae3fbc3a7433d30268b38c9cfe46e6

**Comment by hermann-p** [comment]
Thanks - I vote to close that issue.
