### ISSUE TITLE
Header anchor tag format

### ISSUE THREAD

**Issue by Deraen** [theJohnnyBrown/endophile#9]
With my changes in #8 it is possible to use Pegdown anchorlinks extension.

The default format for them is:
`{:tag :h1, :content [{:tag :a, :attrs {:name "foo" :href "#foo"}, :content ["Foo"]}]}`

And I'm wondering how others like that the header text is wrapped inside a tag. Alternative would be to  format the data like this:
`{:tag :h1 :content [{:tag :a, :attrs {:name "foo"}} "Foo"]}`

I have already implemented the changes in this branch, with a option to toggle the format: https://github.com/Deraen/endophile/compare/master...Deraen:conversion-options?expand=1

(It requires changes from #8)

I would like to hear what others think about formatting anchor links and if the option is required or if just one format should be supported?
Also might there in future be need for other options for `to-clj`/`to-hiccup`?

**Comment by theJohnnyBrown** [comment]
So, I haven't had my head in markdown-land for a little while now - would it be ok if I give you write access to the project and do what you think is best here?

**Comment by podviaznikov** [comment]
@theJohnnyBrown can you please push the latest version to Clojars?

**Comment by Deraen** [comment]
@theJohnnyBrown If you want, you can give me write access on GitHub and Clojars and I can take care of this (and other issues/prs).

**Comment by Deraen** [comment]
Ping @theJohnnyBrown

**Comment by Deraen** [comment]
In fact this change will be unnecessary as Pegdown now has an extension to control the format on header anchors.
